version: "3"
tasks:
    install:
        cmds:
            - go install

    plan:
        dir: demo/
        cmds:
            - terraform plan

    apply:
        dir: demo/
        cmds:
            - terraform apply -auto-approve

    destroy:
        dir: demo/
        cmds:
            - terraform destroy

    docs:
        cmds:
            - go generate ./...

    build-plan:
        cmds:
            - { task: "install" }
            - { task: "plan" }

    build-apply:
        cmds:
            - { task: "install" }
            - { task: "apply" }

    build-destroy:
        cmds:
            - { task: "install" }
            - { task: "destroy" }
