version: "3"
tasks:
  install:
    cmds:
      - go install

  plan:
    dir: examples/
    cmds:
      - terraform plan

  apply:
    dir: examples/
    cmds:
      - terraform apply

  build-plan:
    cmds:
      - { task: "install" }
      - { task: "plan" }

  build-apply:
    cmds:
      - { task: "install" }
      - { task: "apply" }
