version: "3"
tasks:
  install:
    cmds:
      - go install

  plan:
    dir: examples/
    cmds:
      - terraform plan

  apply:
    dir: examples/
    cmds:
      - terraform apply -auto-approve

  destroy:
    dir: examples/
    cmds:
      - terraform destroy


  build-plan:
    cmds:
      - { task: "install" }
      - { task: "plan" }

  build-apply:
    cmds:
      - { task: "install" }
      - { task: "apply" }

  build-destroy:
    cmds:
      - { task: "install" }
      - { task: "destroy" }
